apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipy
      flomesh.io/app: pipy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipy
        flomesh.io/app: pipy
    spec:
      containers:
        - name: pipy
          image: flomesh/pipy:0.90.2-41
          command:
            - sh
            - -c
            - |
              pipy http://fgw-repo:6060/repo/local/fgw/
