{
 "title": "Flomesh gateway (FGW)",
 "description": "Flomesh gateway (FGW)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(fgw_http_status,service)"
    }
   },
   {
    "name": "route",
    "query": {
     "query": "label_values(fgw_http_status,route)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(fgw_http_status,instance)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(fgw_http_status,consumer)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(fgw_http_status,node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pipy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fgw_http_requests_total{instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fgw_http_current_connections{state=\"accepted\", instance=~\"$instance\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fgw_http_current_connections{state=\"handled\", instance=~\"$instance\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Pipy connection state",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fgw_http_current_connections{state=~\"active|reading|writing|waiting\", instance=~\"$instance\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fgw_bandwidth{instance=~\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(fgw_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(fgw_bandwidth{type=\"ingress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fgw_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(fgw_bandwidth{type=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Requests per second (RPS) by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fgw_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (code)",
     "legendFormat": "HTTP Status:{{code}}"
    }
   ]
  },
  {
   "title": "Requests per second (RPS) per service/route",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fgw_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(rate(fgw_http_status{service=~\"$service\",route=~\"$route\",instance=~\"$instance\"}[$__rate_interval])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(fgw_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fgw_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fgw_http_latency_bucket{type=~\"request\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "FGW Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(fgw_http_latency_bucket{type=~\"fgw\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fgw_http_latency_bucket{type=~\"fgw\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fgw_http_latency_bucket{type=~\"fgw\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(fgw_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fgw_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(fgw_http_latency_bucket{type=~\"upstream\",service=~\"$service\",consumer=~\"$consumer\",node=~\"$node\",route=~\"$route\"}[$__rate_interval])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Pipy internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Pipy pool allocated",
   "type": "timeseries",
   "description": "pipy 分配的内存",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pipy_pool_allocated_size{class=\"\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Pipy pool spare",
   "type": "timeseries",
   "description": "pipy 空闲的内存\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(pipy_pool_spare_size{class=\"\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}