global:
  scrape_interval:     30s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:

#  - job_name: 'pipy-sd'
#    scrape_interval: 30s
#    http_sd_configs:
#      - url: http://192.168.12.5:30000/api/sd   # http://<flomesh-gui地址>/api/sd
#        refresh_interval: "30s"
#        follow_redirects: true

  - job_name: 'pipy-repo'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 192.168.122.188:5050         # pipy repo 地址

